name: Release workflow

on:
  release:
    types: [created]

jobs:
  release:
    name: Publish binaries to release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish x86_64-unknown-linux-musl binary
        uses: rust-build/rust-build.action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: x86_64-unknown-linux-musl
          EXTRA_FILES: 'README.md LICENSE'
